In [16]:
import numpy as np

arr = np.array([1,2,4])
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
#print(arr.size)

sum=0
for i in range(0,len(arr)):
    sum+=arr[i]
print(sum)

int64
(3,)
1
7


In [25]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [29]:
arr =  np.array([[1,2,3],[3,4,5]])
arr2 =  np.array([[1,2,3],[3,4,5],[5,6,7]])

result = arr @ arr2
print(result)


[[22 28 34]
 [40 52 64]]


In [31]:
arr = np.array([1,2,3,4])
p = arr ** 2
print(arr,p)

[1 2 3 4] [ 1  4  9 16]


In [38]:
arr2 =  np.array([[1,2,3],[3,4,5],[5,6,7]])
print(np.sum(arr2,axis=0))
print(np.sum(arr2,axis=1))

[ 9 12 15]
[ 6 12 18]


In [76]:
arr2 =  np.array([[1,2,3],[3,4,5],[5,6,7]])
nor = arr2.mean()
print(nor)
res = arr2.sum()-nor/9
print(res)
      

4.0
35.55555555555556
